### PR TITLE
Create text.txt

### PR DESCRIPTION
**Pull request by Princesince2001**

### CODE REVIEW

**Comment by Princesince2001** [comment]
Mr.Rajkumar, please check my code and share me the status.

**Comment by Rajkumar0828** [comment]
Hi Vasan, I see you code, the code format is good, I suggest
to maintain name convention in class name by pascal naming convention
format.
 It Promotes the code standard

**Comment by Princesince2001** [comment]
Sure Raj, I will change it immediately, thanks for your valuable comment.

**Comment by Rajkumar0828** [comment]
Sure vasan after resolving again make the pull  Request

**Comment by Princesince2001** [comment]
Resolved.

**Comment by Rajkumar0828** [comment]
Ok vasan

**Pull request merged**
